# Site settings
baseURL = "https://caitlynralph.github.io/"
languageCode = "en-us"
title = "Caitlyn"
theme = "forty"
publishDir = "/Users/caitlynralph/Downloads/personalwebsite/caitlynralph.github.io"

disqusShortname = "caitlynralph"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-112533031-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Caitlyn"
  description = "Caitlyn Ralph's personal website"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = ""

  # Navigation Section
  [params.navigation]
    title = "Portfolio"
    subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About"
      url = "about"

    [[params.navigation.links]]
      name = "Data Visualization"
      url = "datavisualization"

    [[params.navigation.links]]
      name = "Writing"
      url = "writing"
      
    [[params.navigation.links]]
      name = "Music Industry"
      url = "musicindustry"
      
    [[params.navigation.links]]
      name = "Thesis"
      url = "thesis"
      
    [[params.navigation.links]]
      name = "Blog"
      url = "blog"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "#"

    # Button Style 2
    # [[params.navigation.button2]]
      # name = "Log In"
      # url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Caitlyn"
    subtitle = "CODER, WRITER, GREEN TEA DRINKER"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "About"
      subtitle = "+ Curriculum Vitae"
      image = "pic01.jpg"
      url = "about"

    [[params.tiles.showcase]]
      title = "Data Visualization"
      subtitle = "Projects"
      image = "pic02.jpg"
      url = "datavisualization"

    [[params.tiles.showcase]]
      title = "Writing"
      subtitle = "Published"
      image = "pic03.jpg"
      url = "writing"

    [[params.tiles.showcase]]
      title = "Music Industry"
      subtitle = "Experience"
      image = "pic04.jpg"
      url = "musicindustry"

    [[params.tiles.showcase]]
      title = "Thesis"
      subtitle = "In Progress"
      image = "pic05.jpg"
      url = "thesis"

    [[params.tiles.showcase]]
      title = "Blog"
      subtitle = "Coming Soon"
      image = "pic06.jpg"
      url = "blog"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "My Story"
    subtitle1a = """Ever since I saw Green Day's """ 
    knowyourenemy = "https://www.youtube.com/watch?v=qUEw35GFNCs"
    subtitle1b = """ music video on TV the summer before 8th grade, I’ve been obsessed with music. I knew my talents weren’t in musical creation, however. I was a naturally analytical person—excelling in math and science before anything else. Yet, I was determined to do something with music, so I joined my middle school newspaper and started writing. Throughout high school, I kept writing and kept listening to music, all while doing four years of competitive science fair."""
    subtitle2a = """By halfway through my college career, I was a computer science major with """
    mrn = "https://www.mrn.org/"
    subtitle2b = """ on my resumé. Simultaneously, I kept writing and kept loving music, """
    ap = "https://www.altpress.com/contributors/profile/caitlyn_ralph"
    subtitle2c = """ on Alternative Press’ remote news team. Over the course of two years, I worked my way to the head of that news team and, while on an semester exchange in Cleveland, to the magazine office’s sole digital assistant, juggling a full-time job and full-time classes in journalism and computer science."""
    subtitle3a = """When summer 2017 arrived, I began freelancing for AP, moved from Cleveland to New York City, and started an internship at data visualization studio """
    polyraph = "http://polygraph.cool/" 
    subtitle3b = """ and its adjoining publication, """
    pudding = "https://pudding.cool/"
    subtitle3c = """ . I worked on """
    clinics = "https://pudding.cool/2017/09/clinics/"
    subtitle3d = """ and frequently assisted with client work at Google for YouTube Music and YouTube Culture and Trends. After the summer internship concluded, I returned to New College to finish my fourth and final year of undergrad. I’m currently writing a senior thesis, creating a visual essay, in the same vein as those on The Pudding, that chronicles the history of """
    band = "http://the1975.com/#"
    subtitle3e = """ through data and interactive graphics."""
    subtitle4a = """As I finished my internship at Polygraph, I had solidified my interest in applying data science and its related skills to creative pursuits, whether that be crafting a visual essay on """
    office = "https://pudding.cool/2017/08/the-office/"
    subtitle4b = """ or doing analytics work for the music industry. My knack for organization, numbers, working with people, and the like has led to an auxiliary but accompanying interest in artist management."""
    subtitle5 = """This portfolio is a journey through my interdisciplinary journey. It displays my work in the various fields related to data storytelling. It also maintains a quiet (and under-construction) blog, (to be) populated with posts on technology (data and its tools), music (indie and punk, mostly British), and lifestyle (hobbies, such as running, bullet journaling, movies, and maybe even some style)."""
    buttonText = "Get Started"
    url = "#"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "caitlyn.ralph14@ncf.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(407) 415-3082"

    [[params.contact.address]]
    title = "New College of Florida"
    street = "5800 Bay Shore Road, Box 766"
    city = "Sarasota, FL 34243"
    country = "United States"

  # Footer section
  [params.footer]
    enable = true
    copyright = ""

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/earthto_caitlyn"
      label = "Twitter"

    # [[params.footer.social]]
      # icon = "fa-facebook"
      # url= "https://www.facebook.com"
      # label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/earthto_caitlyn"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/caitlynralph"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/caitlynralph"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
